version: '2'
services:
  update-daemon:
    build: ./update-daemon
    restart: always
    volumes:
      - "/docker/web/wwwroot:/srv/http"
      - "/etc/localtime:/etc/localtime"
    links:
      - db
  db:
    image: postgres:9.4
    volumes:
      - "/docker/tt-rss/db:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime"
    restart: always
    environment:
      POSTGRES_PASSWORD: ttrss
      POSTGRES_USER: ttrss
      POSTGRES_DB: ttrss
      PGDATA: /var/lib/postgresql/data/pgdata
  web:
    image: nginx:stable
    volumes:
      - "/docker/web/wwwroot:/srv/http"
      - "/docker/web/config/site.conf:/etc/nginx/conf.d/site.conf"
      - "/docker/web/config/certs:/etc/nginx/certs"
      - "/etc/localtime:/etc/localtime"
    ports:
      - "443:443"
    links:
      - db
      - php
  php:
    build: ./php
    volumes:
      - "/docker/web/wwwroot:/srv/http"
